sudo: required
dist: trusty
language: generic
services:
  - docker
script:
  - docker build . -t kubevirt/libvirt
  - docker run --rm -it kubevirt/libvirt libvirtd --version
deploy:
- provider: script
  script: ./deploy.sh
  skip_cleanup: true
  on:
    branch: master
env:
  global:
    - secure: OsEUfhA4Jz73Rb2U5E65hfMf/3avl4zoos+PZWBHT+qG2GgbUZO4K5qVevdkj4iy1BWXWwQW24xGDQEU24btc0SlqlYfC3K3m2axVmFRd/fYj5RtpoACeFzX6FOCUfwd9YOeihO2IcIBdwZczruZgKZk4ur2ozI7cxz7uJNY6sepvPHf/JdvCGYwaIEb02V87YOTWn8DzfQZXNc5LP/elpuulk8AfjfpRTvjlbXxRQmNHrWpqcNBM7o/qy9iV7fWvCUdIMFm8FyBFrxvZtnRn5ECg4AKAkX4MZmllKtmVF8I7dJOnPwTbTIsKdC5BtJ93X0KpEeElTN37N/e3N1qDmgVqmpVFBtWElFdRqk433GCGJaWJiuq2k12HoXmMelIfB7E1PdGNebggZclb1cSWGdQDj6ynkh+mdivWyCckBb7wtzOQ1bbxjIo6mUOsCAEOssY6/Ugssis6Oh1yEPPIaZJ5FdTTxy2T2xHUZ/ZzQ9k+iPZr6H/Gt2PJSqsHI10liFF7Xmjb6K5BVPbzUxWho8WlKK/glTMG9aucp5vP++bSGkiwjzeyiF4xWoIKdddPab1/CY4HMBgKa5J8eRUkTndIyfwf8MsLz7Ea3YYrdMmbQ123r1N93TJ2+ap6zRup0FTVPVc20hqBPap/9kJUxNuIDVtJM120z5DxYkNtqs=
    - secure: jHCrETcBied7j+wXQ8YJR5CdNtEy2ZZssJyRD4ORDsSkJwRkh3tD+zJs9WdweCY2NrM4jwSOmJsodyG7a3D5Cn5K+ZQXuW4JbjLFcwftyjHJXvskkxswSzSTuoAA8vIPjDEwiiy24NYCvpNkuF/2Bgrqeg2Bm1hAm0y/GwZQHY8M6dq2myTkL+4lc7ZDHEDXLgZ7wRfd/CXuyY6i852ndz65BtafdvYKqNf/GBzO/5x59jLVA5ue2kdeZ0RyNsgCTsGyIx0nlBx6nwzhb+RgSVwl2SODfei3oiOu3L0uqQOZS61I0x8DiD0wAwAmKU6j5BeeVfQDgY6uaqDeRahv4C6dPbSHg3YO4TfBl78UipaBDhVRW4D6uFCQ/yZAPNFTNhRCHHVNDvaqtX/h5qag92jQdH7IcBUjM/baGgisoZ5A9DyWKei8uKrar3erfjPtMRvLuuaGuluCbmufshBWBtzW6gucwEL7QVnuQRbzL0qTcaDIKLDXaKCToTGjNryNMqGKpH8+qPv3d/pn2yOb61lYJbJfVDZlUgIjvFxe0ZDIlLApJtdiNyL1zKyozL+aK8QVrlvXAHn3uraz9l3+HL8bC7cn7EEig95aAgpi/5GjHmTDE+vLO5NU9An/Zbl0LXSW0gBv1JrNakib3l9t9bCYVWJ7oL2gemxrLm+4MeM=
