sudo: required
dist: trusty
services:
- docker
script:
- docker build . -t kubevirt/libvirt
deploy:
- provider: script
  script: docker login -u="$DOCKER_USER" -p="$DOCKER_PASS" && docker push kubevirt/libvirt
  skip_cleanup: true
  on:
    branch: master
env:
  global:
  - secure: Fw4shBL1cBgLus76Z7Odh5Fohl0Df7OB2AmqvFtp09Y9XXiTXWiQ9llBoL5sAj5V/Gd10VBQkeUskijXq58jw823QTOFJ4fH7H1xfGU4H383yfrOgWiNG0949NSX0E6WH/0XcLcmZfMtKjALnsDIXWEP74X/EIftyY9MPFyPmrxT2f56RxriiPzeOnCQZMijBn9jcuxV1Tu2FUS1hHY/mCs2o3dNBqz5CCTk6dOspDJNZYYiiyrV+oSp/zkp4IzaxsQ8GoFj61w11noayKEkSDMgikddxIKJdG0H8JvZcJ2g+5yEG6sPzYnufvl9cbaIw10/ZETfkZrNlZub+hEXleQKWd8D4H9n95hFua2Ki2Fk7+m5upkeMEyxDXauiQNIzbFrevzkqy/VNFK8xpgeDnvxIK1vny4+f9GJTN9qXpXTHB/izC2QhqdAYRJ23lctJsDfExO2yvZKy5gnwwIr8dLWGL7Yr389PLd+pTq11rtkQ7RleXDvxnXFiSU+L4iwAym4D5n+ikgWsYBfV/xC6EydZRHn9BoDj+u0Av6HUWpfSuWRhts3GeECUenb81+CgMx5dFlGpx3y7Jq2Fato4+i1A5GPVv30dpiXtIjwuxiWqXAO3aEhoUWmSKC3XM9+AxYce8ci6Yc9TV604yczcC42m64ciomLaWtuy0lguzw=
  - secure: PLo/VyfUjloDGEoXk0r/K778khksA+FQxaFEPLRBDeNDSvrjhztlA4ppwf8PQYu4IqzvaD2doH7Dv1sY4v34ZQtxW1Dx9utxexiLaaQWujHnxsRLUVhU4/5wQKD00FWGjcmx+oysRIh9iysR1lsBABxPq9Nz6MTec2lVToaMLfMi9IlfCa23PhM+Rf8R9JGf5QfbspkY/7Jx/CDXyw6fwtb57p2XJf3x8rVXGcVQrFEYxs1C8DFddncTx4P5sOGEHyUoO31/XylM/NZp2lJvr/G9ye7RgVfvBMckWLVYcunR5NatAu/MJhH4+PLDoW+q48b4ElDPX/HZ2aGytce6pK+jY9/gBxhes/eYeAX2FXU//ev/E8hMUvmQSjBdoJdWXgdJ/k+GAp3bWbe4DbRsnN26XV+pes+CMgIfYTPAkrW3Q7kdRtI1ZfqR/5TB2UfxkwdB88YU33aYCwfIlcVBW7Htl0SAFudSm8mY+eCyCr2ZeieDgWht6VPGuX49aQNKtJgha+vCV4A1bSKwkA1O/asLKozw0NmoGE75fxrz/KZ2DAjLRYQNj6FyFoOLMBoLIl1ZeKgmPOTk8/HKRBtn0Hwt0XHeKlMr5mimFIslnQqAmk30iJESV8IHgSnmXOmrExT/bmOzoshXvjkv8WOMrevY+FaOE+BU7dg6pRgN4hM=
